config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :photos, except: [:index, :show]
  get 'gallery' => 'photos#index'

    root 'welcome#landing'
    get 'home' => 'welcome#index'
    get 'blogs' => 'blogs#index'
    get  'blogs/new' => 'blogs#new'
    get 'subscribe', to: 'subscribers#new'
    post 'subscribe', to: 'subscribers#create'
    
    resources :blogs, only: [:create, :show, :edit, :update, :destroy]
    resources :categories, param: :name, except: [:update, :edit]
    resources :categories, only: [:update, :edit]

  
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  has_many :blog_categories
  has_many :categories, through: :blog_categories
  validates :title, presence: true, length: { minimum: 5, maximum: 30 }, uniqueness: { case_sensitive: false }
  validates :description, presence: true, length: { minimum: 10, maximum: 50000}
  validates :user_id, presence: true
  mount_uploader :picture, PictureUploader
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
 
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :is_admin, only: [:edit, :new, :update, :destroy]
  
  def index
    @blogs = Blog.paginate(page: params[:page], per_page: 5)
    @photos = ['kiadesk.jpg', 'kiacongress.jpg', "kiabag.jpg", "kiarunback.jpg"]
  end
  
  def show
    @photos = ['kiadesk.jpg', 'kiacongress.jpg', "kiabag.jpg", "kiarunback.jpg"]
  end
  
  def new
    @blog = Blog.new
  end
  
  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user
      if @blog.save
        flash[:success] = "Blog was succesfully created"
        Subscriber.all.each do |subscriber|
          SubscribeMailer.blog_email(subscriber, @blog).deliver
        end
        redirect_to blog_path(@blog)
      else
        render 'new'
      end
  end
  
  def edit
    
  end
  
  def update
    if @blog.update(blog_params)
      @subscriber = Subscriber.first
      flash[:success] = "Blog was succesfully updated"
      redirect_to blog_path(@blog)
    else
      render 'edit'
    end
  end
  
  def destroy
    @blog.destroy
    flash[:danger] = 'Blog was succesfully deleted'
    redirect_to blogs_path
  end
  
  private
  
  def blog_params 
    params.require(:blog).permit(:title, :description, :picture, category_ids: [])
  end
  
  def set_blog
    @blog = Blog.find(params[:id])
  end
  
  def is_admin
    if logged_in?
       if !current_user.admin?
         redirect_to home_path
       end
    else
      flash[:danger] = "You do not have the proper permissions to access this page"
      redirect_to home_path
    end
  end

end

app/views/blogs/_blog_form.html.erb
<%= render 'shared/errors', obj: @blog %>


<div class='row'>
 <div class='col-xs-12'>
    <%= form_for(@blog, :html => {class: "form-horizontal", role: "form"}) do |f| %>
   <div class='form-group'>
     <div class="control-label col-sm-2">
        <%= f.label :title %> 
     </div>
     <div class="col-sm-8">
        <%= f.text_field :title, class: "form-control", placeholder: "Title of blog", autoFocus: true %>
     </div>
   </div>
   <div class='form-group'>
     <div class="control-label col-sm-2">
        <%= f.label :description %>
     </div>
     <div class="col-sm-8">
        <%= f.cktext_area  :description,  class: "form-control", rows: 20, placeholder: "Blog content" %>
     </div>
   </div>
    <div class="form-group">
      <div class="row">
         <div class="col-sm-offset-2 col-sm-8">
           <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
            <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
           <% end %>
      </div>
      </div>
         </div>
   <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :picture %><br>
    </div>
   <div class="col-sm-3">
    <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png", :class => 'form-control' %>
   </div>
  </div>
    <div class="form-group">
         <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary btn-lg" %>
      </div>
         </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel and go back to blogs", blogs_path %> ]
   </div
     </div>
</div>

app/views/blogs/_blogs.html.erb
<% obj.each do |blog| %>
<div class="row blog-list">
  <div class="col-md-3 col-md-offset-1 blog-list-title">
    <h3><%= link_to blog.title, blog_path(blog) %></h3>
    <h4>Akia Callum</h4>
  </div>
  <div class="col-md-4 blog-body-list">
    <p>
      
      <%= simple_format raw(blog.description.truncate(1000)), class:".blog-body-list" %>
    </p>
    <div style="float:left">
    <div style="padding-top:10px">
      <small>Last updated <%= time_ago_in_words(blog.updated_at)  %> ago </small></br>
      <small>Posted <%= time_ago_in_words(blog.created_at)  %> ago </small></br>
    </div>
    <div style="padding-top:10px">
      <small class="view-blog"><%= link_to "View Blog", blog_path(blog) %></small>
      <small><br><br>
        <% Category.all.each do |category| %>
          <small class="view-blog"><%=link_to category.name, category_path(category.name) %></small>
        <% end %>
      </small></br>
    </div>
    <div style="padding-top:10px">
      <% if logged_in? && current_user.admin? %>
           <%= link_to "Edit blog", edit_blog_path(blog), class: "btn btn-xs btn-primary" %>
           <%= link_to "Delete blog", blog_path(blog), method: :delete,
               data: { confirm: 'Are you sure you want to delete this article'},
               class: "btn btn-xs btn-danger"%>
      <% end %>
    </div>
    </div>
  </div>
  <div class="col-md-4">
    <% if blog.picture? %>
      <%= image_tag blog.picture.url, class:"img-responsive blog-img" %>
    <% else %>
      <%= image_tag @photos.sample, class:"img-responsive blog-img" %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
  <hr> 
  </div> 
</div>

<% end %>


<style>
  p img {
       height: 400px !important;
  }
</style>

app/views/blogs/edit.html.erb
<h3 align="center">
  Edit Blog
</h3>

<%= render 'blog_form' %>

app/views/blogs/index.html.erb
<%= render 'blogs.html', obj:@blogs %>

<div class="text-center">
  <%= will_paginate %>
</div>

app/views/blogs/new.html.erb
<h2 align="center">
  New Blog Post
</h2>

<%= render 'blog_form' %>

app/views/blogs/show.html.erb
<div class="blog-detail">
  <div class="contain">
    <div class="background-image" id="bgslide" style="width:100%"></div>
    <h1 align="center">
      <%= @blog.title %>
    </h1>
    <h4 align="center">
      Akia Callum
    </h4>
  </div>
  <div class="blog-body col-md-8 col-md-offset-2">
    <div style="display:block">
    <p>
      <%= raw(@blog.description) %>
    </p>
    <div align="center">
      <h4 style="padding-top:30px" class="subscribe-btn"><%= link_to "Subscribe", subscribe_path %></h4></br></br>
      <small>Last updated <%= time_ago_in_words(@blog.updated_at)  %> ago </small></br>
      <small>Posted <%= time_ago_in_words(@blog.created_at)  %> ago </small></br>
    </div>
      <div align="center">
      <small>
        <% if logged_in? && current_user.admin? %>
             <%= link_to "Edit blog", edit_blog_path(@blog), class: "btn btn-xs btn-primary" %></br>
             <%= link_to "Delete article", blog_path(@blog), method: :delete,
                 data: { confirm: 'Are you sure you want to delete this article'},
                 class: "btn btn-xs btn-danger"%>
        <% end %>
      </div>
    </small>
      </div>
    </div>
</div>

<style>
.background-image {
  left: 0;
  right: 0;
  //z-index: 1;

  display: block;
  background-image: url(<% if @blog.picture? %> 
                        <%= image_path @blog.picture.url %>
                        <% else %>
                        <%=image_path @photos.sample %>
                        <% end %>);
  width: 100%;
  height: 700px;
  opacity: 0.92;
  background-size: cover;
  -webkit-filter: blur(0.5px);
  -moz-filter: blur(0.5px);
  -o-filter: blur(0.5px);
  -ms-filter: blur(0.5px);
  filter: blur(0.5px);
  border-radius: 100px;
}
  
</style>

<script>

// function changeImage() {
//     $('.background-image').css("background-image", "url('<%= image_path @photos.sample %>' )" )
//  }
 // $('.background-image').css("background-image", "url('<% @blog.picture.url if @blog.picture? %>')")
  console.log("<%= @blog.picture.url %>")
   <% if @blog.description.length < 100 %>
      $('.blog-body').addClass("text-center")                 
   <% end %>
</script>