config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :photos, except: [:index, :show]
  get 'gallery' => 'photos#index'

    root 'welcome#landing'
    get 'home' => 'welcome#index'
    get 'blogs' => 'blogs#index'
    get  'blogs/new' => 'blogs#new'
    get 'subscribe', to: 'subscribers#new'
    post 'subscribe', to: 'subscribers#create'
    
    resources :blogs, only: [:create, :show, :edit, :update, :destroy]
    resources :categories, param: :name, except: [:update, :edit]
    resources :categories, only: [:update, :edit]

  
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @latest_blogs = Blog.limit(2).order('id desc')
    @latest_photos = Photo.limit(10).order('id desc')
  end
  
  def landing 
    
  end
end
  

app/views/welcome/index.html.erb
<div class="container-fluid" style="padding-top:50px">
<h1 align="center" style="padding-top:5px;padding-bottom:40px">[Insert Quote or something here]</h1>
<div class="row">
<div class="col-md-5">
  <%= image_tag "kiarunback.jpg", class:"img-responsive land-img" %>
  </div>
  <div class="col-md-2">
    <div align="center">
      <%= image_tag 'kiatrack.jpg', class:'img-circle frontimg img-responsive animationimg' %>
    </div> 
    <div class="welcomeabout" align="center">
      <h4 style="" class="opac">About Kia</h4>
      <p style="padding-top:10px;font-size:1em;font-weight:700" class="opac">
          [About/Bio Here]
      </p>
      </br><h4 class="view-blog"><%=link_to "Subscribe", subscribe_path %></h4>
    </div>
  </div>
<div class="col-md-5">
  <%= image_tag "kiarunstart.jpg", class:"img-responsive land-img" %>
  </div>
</div>
</div>

<div class="container-fluid" id="content-section">
  <div class="row">
    <div class="col-md-6">
      <% if @latest_blogs.any? %>
      <h2 align="center" style="font-weight:900">Latest Blogs</h2>
      <% end %>
        <% @latest_blogs.each do |blog| %>
        <div style="padding-bottom:20px">
            <h3 align="center" style="font-weight:700"><%= blog.title %></h3>
            <p class="description"><%= simple_format raw(blog.description.truncate(5000)), class:".blog-body-list" %></p>
            <div style="padding-top:10px">
              <small>Last updated <%= time_ago_in_words(blog.updated_at)  %> ago </small></br>
              <small>Posted <%= time_ago_in_words(blog.created_at)  %> ago </small></br>
          </div><br>
            <p class="view-btn"><%= link_to "View Blog", blog_path(blog) %></p>
        </div>
        <% end %>
      
    </div>
    <div class="col-md-offset-1 col-md-5">
      <% if @latest_photos.any? %>
        <h2 align="center" style="font-weight:900">Latest Photos</h2>
      <% end %>
      <% @latest_photos.each do |photo| %>
      <div class="col-md-6 index-gallery" style="padding-bottom:10px"><%= image_tag photo.picture.url %></div>
      <% end %>
    </div>
  </div>

</div>

  
  <div class="container">
<div class="row" style="padding-top:75px;padding-bottom:30px">
  
  
  <div class="col-md-4 index-img-container">
    <%= image_tag '1.jpg', class: 'img-responsive index-img' %>
    <small class="index-btn hidden"><%= link_to "View Blogs", blogs_path %></small>
  </div>
  
    <div class="col-md-4 index-img-container">
    <%= image_tag 'kiareddress.jpg', class: 'img-responsive index-img' %>
    <small class="index-btn hidden"><%= link_to "View Gallery", gallery_path %></small>
  </div>
  
    <div class="col-md-4 index-img-container">
    <%= image_tag 'kiasign.jpg', class: 'img-responsive index-img' %>
   <small class="index-btn hidden"><%= link_to "View Categories", categories_path %></small>
  </div>

    
  </div>
</div>

<style>
  p img {
       height: 500px !important;
  }
</style>

app/views/welcome/landing.html.erb
<div id="landing-container" class="container-fluid">
<!--   <h1 align="center" style="font-weight:800">
    [Insert Something Here]
  </h1> -->
  <div class="col-md-5 col-md-offset-4 text-center">
      <h2 style="margin-top:5%;margin-left:40px;font-weight:900;font-size:50px">Coming Soon ... </h2>
  </div>
  
  <script>
    $('h2').hide()
    $('h2').fadeIn(3000)
    
  </script>

  <div class="row">
    <div class="enter col-md-3 col-md-offset-5">
    <h1><%= link_to "Enter", home_path %></h1>
    </div>
  </div>
  
  <div class="view col-md-7 col-md-offset-4">
    <div class="margin-left">
      <h3><%= link_to "View Blogs", blogs_path %></h3>
      <h3><%= link_to "View Photos", gallery_path %></h3>
      <h3><%= link_to "View Categories", categories_path %></h3>    
    </div>
  </div>
  
  <div class="col-md-4 col-md-offset-5">
    <%=link_to(image_tag('fblogo.png'), "https://www.facebook.com/akia.callum") %>
    <%=link_to(image_tag('instalogo.png'), "https://www.instagram.com/akiascallum/") %>
    <strong><h4 style="font-size:33px;font-weight:900;display:inline;color:black"></strong>
      @akiascallum
    </h4>
  </div>
  
</div>





<script>
  $(".navigation").hide();
  $('.page-container').removeClass("container-fluid");
</script>