config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :photos, except: [:index, :show]
  get 'gallery' => 'photos#index'

    root 'welcome#landing'
    get 'home' => 'welcome#index'
    get 'blogs' => 'blogs#index'
    get  'blogs/new' => 'blogs#new'
    get 'subscribe', to: 'subscribers#new'
    post 'subscribe', to: 'subscribers#create'
    
    resources :blogs, only: [:create, :show, :edit, :update, :destroy]
    resources :categories, param: :name, except: [:update, :edit]
    resources :categories, only: [:update, :edit]

  
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :blog_categories
  has_many :blogs, through: :blog_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25}
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :destroy]
  before_action :is_admin, only: [:new, :edit, :destroy, :update]
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created succesfully"
      redirect_to category_path(@category.name)
    else
      render 'new'
    end
  end
  
  def show
    @categories = @category.blogs.paginate(page: params[:page], per_page: 5)
    @photos = ['kiadesk.jpg', 'kiacongress.jpg', "kiabag.jpg", "kiarunback.jpg"]
  end
  
  def index
    @categories = Category.paginate(page: params[:page], per_page: 10)
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
      if @category.update(category_params)
        flash[:success] = "Category name was succesfully updated"
        redirect_to category_path(@category.name)
      else
        redirect_to root_path
      end
  end
  
  def destroy
    @category.destroy
    redirect_to categories_path
  end    
  
  private
  
  def is_admin
    if logged_in?
       if !current_user.admin?
         redirect_to home_path
       end
    else
      flash[:danger] = "You do not have the proper permissions to access this page"
      redirect_to home_path
    end
  end
  
  def category_params
    params.require(:category).permit(:name)
  end
  
  def set_category
    @category = Category.find_by(name: params[:name])
  end
  
end

app/views/categories/_category_form.html.erb
<%= render 'shared/errors', obj: @category %>


<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class='form-group'>
 <div class="control-label col-sm-2">
    <%= f.label :name %> 
 </div>
 <div class="col-sm-8">
    <%= f.text_field :name, class: "form-control", placeholder: "Category name", autoFocus: true %>
 </div>
</div>
<div class="form-group">
     <div class="col-sm-offset-2 col-sm-10">
  <%= f.submit class: "btn btn-primary btn-lg" %>
  </div>
     </div>
<% end %>
<div class="col-xs-4 col-xs-offset-4">
  [ <%= link_to "Return to blog", blogs_path %> ]
</div

app/views/categories/edit.html.erb
<%= render 'category_form' %>

app/views/categories/index.html.erb
<h1 align="center">
  Listing All Categories
</h1>

<div align="center">
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="well custom-well col-md-4 col-md-offset-4">
          <li class="blog-title">
            <%= link_to category.name, category_path(category.name) %>
          </li>
          <li><small><%= pluralize(category.blogs.count, "blog") %></small></li>
        </div>
      </div>
  </ul>
  <%  end %>
  <%= will_paginate %>
  </div>

app/views/categories/new.html.erb
<%= render 'category_form' %>

app/views/categories/show.html.erb
<h1 align="center" style="font-weight:800">
  <%= @category.name %>
  <% if logged_in? and current_user.admin? %>
    <div class="row">
       <span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
    </div>
     <%= link_to "Delete Category", category_path(@category.name), method: :delete,
               data: { confirm: 'Are you sure you want to delete this category'},
               class: "badge", style:"color:black" %>
  <% end %>
</h1>
<hr>

<%= render 'blogs/blogs', obj:@categories %>
<div class="text-center">
  <%= will_paginate %>
</div>