config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :photos, except: [:index, :show]
  get 'gallery' => 'photos#index'

    root 'welcome#landing'
    get 'home' => 'welcome#index'
    get 'blogs' => 'blogs#index'
    get  'blogs/new' => 'blogs#new'
    get 'subscribe', to: 'subscribers#new'
    post 'subscribe', to: 'subscribers#create'
    
    resources :blogs, only: [:create, :show, :edit, :update, :destroy]
    resources :categories, param: :name, except: [:update, :edit]
    resources :categories, only: [:update, :edit]

  
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  

end

app/views/layouts/_adminlist.html.erb
<li class="navli">New Blog Post</li>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    

<% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}" %>'>
      <a href='#' class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
    <% end %>
</div>
</div>
  

app/views/layouts/_nav.html.erb
<ul class="navigation text-center" align="center">
  <%= link_to "Home", home_path, class: "navli" %>
  <%= link_to "Blogs", blogs_path, class:"navli" %>
  <%= link_to "Gallery", gallery_path, class:"navli" %>
  <li class="dropdown navli">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <% Category.all.each do |category| %>
        <li><%= link_to category.name, category_path(category.name) %></li>
      <% end %>
      <li role="separator" class="divider bg-primary-cl"></li>
      <li><%= link_to "All Categories", categories_path %></li>
<!--       <li><a href="#">Action</a></li>
      <li><a href="#">Another action</a></li>
      <li><a href="#">Something else here</a></li>
      <li role="separator" class="divider"></li>
      <li><a href="#">Separated link</a></li> -->
    </ul>
  </li>
  <% if logged_in? && current_user.admin? %> 
    <%= link_to "Logout", logout_path, method: :delete, class: "navli" %>
  <% end if %>
  <% if logged_in? && current_user.admin? %> 
  <li class="dropdown navli">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Create <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><%= link_to "New Blog Post", blogs_new_path %></li>
      <li><%= link_to "New Photo", new_photo_path %></li>
      <li><%= link_to "New Category", new_category_path %></li>
    </ul>
  </li>
  <% end if %>
  <% if logged_in? && current_user.admin? %> <li style="list-style:none;display:none"></li>
  <% end if %>
  <li class=""><%=link_to(image_tag('facebook.png'), "https://www.facebook.com/akia.callum") %></li>
  <li class=""><%=link_to(image_tag('instagram.png'), "https://www.instagram.com/akiascallum/") %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Akiascallum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<!--   <script src="//cdn.jsdelivr.net/jquery.color-animation/1/mainfile"></script> -->
<!-- <script
  src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"
  integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E="
  crossorigin="anonymous"></script> -->
<meta name="viewport" content="width=device-width" />
<meta property='og:title' content='Akia S. Callum'/>
<meta property='og:image' content="<%= asset_url('15.jpg') %>"/>
<meta property='og:description' content="Akia's Personal Blog"/>
<meta property='og:url' content='https://akiascallum.herokuapp.com/' />
  <%= csrf_meta_tags %>
</head>
  
<body>
<%= render 'layouts/nav' %>
<%= render 'layouts/messages' %>
  <div class="page-container container-fluid">
<%= yield %>
</div>
 


</body>
</html>